name: Run unit-tests with Jest
on:
  push:
    branches:
      - master

    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - 'yarn.lock'
      - 'babel.config.js'
      - '.github/workflows/unit-tests.yml'

  pull_request:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - 'yarn.lock'
      - 'babel.config.js'
      - '.github/workflows/unit-tests.yml'

defaults:
  run:
    shell: 'bash'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: yarn install --frozen-lockfile
      - run: yarn run test
